#!/usr/bin/env python3
# coding=utf-8

"""
Main app "Edward" for Trololo lib.
"""

import sys

if __name__ == "__main__":
    from trololo.app import TrololoApp
    try:
        TrololoApp().run()
    except Exception as err:
        sys.stderr.write("General error: {}\n".format(err))
