#!/usr/bin/env python3
# coding=utf-8

"""
Main app "Edward" for Trololo lib.
"""

if __name__ == "__main__":
    import sys
    from trololo.app import TrololoApp

    try:
        TrololoApp().run()
    except Exception as err:
        sys.stderr.write("General error: {}\n".format(err))
